#!/usr/bin/env python3
"""Generate Rust kernel embedding code for T5 Flash Attention.

Produces:
  - out/generated/neso_metal_gen.rs  (Metal kernels + loader)
  - out/generated/neso_d3d12_gen.rs  (DXIL kernels + loader)
"""
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUT = SCRIPT_DIR / "out"
GEN_DIR = OUT / "generated"


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        try:
            if path.read_text() == content:
                return False
        except Exception:
            pass
    path.write_text(content)
    return True


def load_metadata():
    sys.path.insert(0, str(SCRIPT_DIR))
    from kernel_configs import KERNEL_METADATA, METAL_KERNELS, HLSL_EXTRA_KERNELS
    return KERNEL_METADATA, METAL_KERNELS, HLSL_EXTRA_KERNELS


def _get_func_name(kernel_name, kernel_list):
    for cfg in kernel_list:
        if cfg[0] == kernel_name:
            return cfg[1]
    return kernel_name


def archive_module(filename, extension):
    return [
        "mod kernel_data {",
        f'    static ARCHIVE: &[u8] = include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/kernels/out/{filename}"));',
        "    static CACHE: crate::kernel_archive::KernelCache = std::sync::OnceLock::new();",
        "    pub fn load_kernel(name: &str) -> anyhow::Result<&'static [u8]> {",
        f'        crate::kernel_archive::load_kernel(name, "{extension}", ARCHIVE, &CACHE)',
        "    }",
        "}",
        "",
    ]


def gen_metal(metadata, metal_kernels):
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    metal_names = [cfg[0] for cfg in metal_kernels]
    encoder_kernels = [n for n in metal_names if n in metadata]

    # Use the scalar Metal lowering on both architectures.  The current Neso
    # simdgroup matmul lowering is not deterministic for the padded short-row
    # shapes used by ModernBERT; the scalar lowering is portable and correct.
    lines.extend(archive_module("kernels_metal_nosimd.tar.zst", "metallib"))

    lines.append("/// Transformer kernel pipelines compiled ahead of time by Neso.")
    lines.append("pub struct NesoKernels {")
    for name in encoder_kernels:
        alias = metadata[name]["alias"]
        lines.append(f"    pub {alias}: ComputePipeline,")
    lines.append("}")
    lines.append("")

    lines.append("impl NesoKernels {")
    lines.append("    pub fn load(metal_device: &MetalDevice) -> Result<Self> {")
    lines.append("        let device = metal_device.device();")
    lines.append("")
    lines.append("        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {")
    lines.append("            let data = kernel_data::load_kernel(name)?;")
    lines.append("            let lib = new_library_with_data(device, data)?;")
    lines.append("            let func = lib")
    lines.append("                .get_function(func_name, None)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Function {func_name} not found in {name}: {e}\"))?;")
    lines.append("            let pipeline = device")
    lines.append("                .new_compute_pipeline_state_with_function(&func)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Pipeline failed for {name}: {e}\"))?;")
    lines.append("            Ok(pipeline)")
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    for name in encoder_kernels:
        alias = metadata[name]["alias"]
        func_name = _get_func_name(name, metal_kernels)
        lines.append(f'            {alias}: load("{name}", "{func_name}")?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def gen_d3d12(metadata, metal_kernels, hlsl_extra):
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    all_names = []
    seen = set()
    for cfg in metal_kernels:
        if cfg[0] not in seen:
            seen.add(cfg[0])
            all_names.append(cfg[0])
    for cfg in hlsl_extra:
        if cfg[0] not in seen:
            seen.add(cfg[0])
            all_names.append(cfg[0])

    d3d12_kernels = [n for n in all_names if metadata.get(n, {}).get("d3d12")]

    if not d3d12_kernels:
        lines.append("// No D3D12 kernels configured")
        return "\n".join(lines).rstrip() + "\n"

    lines.extend(archive_module("kernels_dxil.tar.zst", "dxil"))

    lines.append("/// Neso-compiled DXIL kernel pipelines for transformer encoders.")
    lines.append("#[allow(dead_code)]")
    lines.append("pub struct NesoD3D12Kernels {")
    lines.append("    pub(crate) gpu: Arc<Gpu>,")
    for name in d3d12_kernels:
        alias = metadata[name]["alias"]
        lines.append(f"    pub(crate) {alias}: ID3D12PipelineState,")
    lines.append("}")
    lines.append("")

    # NesoD3D12Kernels::load()
    all_configs = list(metal_kernels) + list(hlsl_extra)
    lines.append("impl NesoD3D12Kernels {")
    lines.append("    pub fn load(gpu: &Arc<Gpu>) -> Result<Self> {")
    lines.append("        let load_pso = |name: &str, dxil: &[u8]| -> Result<ID3D12PipelineState> {")
    lines.append("            gpu.create_compute_pso(dxil)")
    lines.append('                .map_err(|e| anyhow::anyhow!("Failed to create PSO for {name}: {e}"))')
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    lines.append("            gpu: gpu.clone(),")
    for name in d3d12_kernels:
        alias = metadata[name]["alias"]
        lines.append(f'            {alias}: load_pso("{name}", kernel_data::load_kernel("{name}")?)?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main():
    metadata, metal_kernels, hlsl_extra = load_metadata()
    GEN_DIR.mkdir(parents=True, exist_ok=True)

    metal_code = gen_metal(metadata, metal_kernels)
    write_if_changed(GEN_DIR / "neso_metal_gen.rs", metal_code)

    d3d12_code = gen_d3d12(metadata, metal_kernels, hlsl_extra)
    write_if_changed(GEN_DIR / "neso_d3d12_gen.rs", d3d12_code)

    print(f"gen_rust: Metal {len(metal_kernels)} kernels, D3D12 {len([n for n in metadata if metadata[n].get('d3d12')])} kernels")


if __name__ == "__main__":
    main()
