#!/usr/bin/env python3
"""Generate Rust kernel embedding code for T5 Flash Attention.

Produces:
  - out/generated/triton_metal_gen.rs  (Metal: kernel_data + T5Kernels + load)
  - out/generated/triton_d3d12_gen.rs  (D3D12: DXIL consts + T5D3D12Kernels + load)
"""
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUT = SCRIPT_DIR / "out"
GEN_DIR = OUT / "generated"


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        try:
            if path.read_text() == content:
                return False
        except Exception:
            pass
    path.write_text(content)
    return True


def load_metadata():
    sys.path.insert(0, str(SCRIPT_DIR))
    from kernel_configs import KERNEL_METADATA, METAL_KERNELS, HLSL_EXTRA_KERNELS
    return KERNEL_METADATA, METAL_KERNELS, HLSL_EXTRA_KERNELS


def _get_func_name(kernel_name, kernel_list):
    for cfg in kernel_list:
        if cfg[0] == kernel_name:
            return cfg[1]
    return kernel_name


def gen_metal(metadata, metal_kernels):
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    metal_names = [cfg[0] for cfg in metal_kernels]
    encoder_kernels = [n for n in metal_names if n in metadata]

    # kernel_data module (aarch64 — simdgroup)
    lines.append("#[cfg(target_arch = \"aarch64\")]")
    lines.append("mod kernel_data {")
    lines.append("    pub fn load_kernel(name: &str) -> Option<&'static [u8]> {")
    lines.append("        match name {")
    for name in metal_names:
        lines.append(f'            "{name}" => Some(include_bytes!("../metal/{name}.metallib")),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # kernel_data module (x86_64 — no simdgroup)
    lines.append("#[cfg(target_arch = \"x86_64\")]")
    lines.append("mod kernel_data {")
    lines.append("    pub fn load_kernel(name: &str) -> Option<&'static [u8]> {")
    lines.append("        match name {")
    for name in metal_names:
        lines.append(f'            "{name}" => Some(include_bytes!("../metal_nosimd/{name}.metallib")),')
    lines.append("            _ => None,")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # T5Kernels struct
    lines.append("/// Compiled Triton kernel pipelines for T5 encoder attention.")
    lines.append("pub struct T5Kernels {")
    for name in encoder_kernels:
        alias = metadata[name]["alias"]
        lines.append(f"    pub {alias}: ComputePipeline,")
    lines.append("}")
    lines.append("")

    # T5Kernels::load()
    lines.append("impl T5Kernels {")
    lines.append("    pub fn load(metal_device: &MetalDevice) -> Result<Self> {")
    lines.append("        let device = metal_device.device();")
    lines.append("")
    lines.append("        let load = |name: &str, func_name: &str| -> Result<ComputePipeline> {")
    lines.append("            let data = kernel_data::load_kernel(name)")
    lines.append("                .ok_or_else(|| anyhow::anyhow!(\"No embedded kernel for {name}\"))?;")
    lines.append("            let lib = new_library_with_data(device, data)?;")
    lines.append("            let func = lib")
    lines.append("                .get_function(func_name, None)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Function {func_name} not found in {name}: {e}\"))?;")
    lines.append("            let pipeline = device")
    lines.append("                .new_compute_pipeline_state_with_function(&func)")
    lines.append("                .map_err(|e| anyhow::anyhow!(\"Pipeline failed for {name}: {e}\"))?;")
    lines.append("            Ok(pipeline)")
    lines.append("        };")
    lines.append("")
    lines.append("        Ok(Self {")
    for name in encoder_kernels:
        alias = metadata[name]["alias"]
        func_name = _get_func_name(name, metal_kernels)
        lines.append(f'            {alias}: load("{name}", "{func_name}")?,')
    lines.append("        })")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def gen_d3d12(metadata, metal_kernels, hlsl_extra):
    lines = []
    lines.append("// Auto-generated by gen_rust.py -- do not edit")
    lines.append("")

    all_names = []
    seen = set()
    for cfg in metal_kernels:
        if cfg[0] not in seen:
            seen.add(cfg[0])
            all_names.append(cfg[0])
    for cfg in hlsl_extra:
        if cfg[0] not in seen:
            seen.add(cfg[0])
            all_names.append(cfg[0])

    d3d12_kernels = [n for n in all_names if metadata.get(n, {}).get("d3d12")]

    if not d3d12_kernels:
        lines.append("// No D3D12 kernels configured")
        return "\n".join(lines) + "\n"

    for name in d3d12_kernels:
        alias = metadata[name]["alias"]
        const_name = f"DXIL_{alias.upper()}"
        lines.append(f'const {const_name}: &[u8] = include_bytes!("../dxil/{name}.dxil");')
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    metadata, metal_kernels, hlsl_extra = load_metadata()
    GEN_DIR.mkdir(parents=True, exist_ok=True)

    metal_code = gen_metal(metadata, metal_kernels)
    write_if_changed(GEN_DIR / "triton_metal_gen.rs", metal_code)

    d3d12_code = gen_d3d12(metadata, metal_kernels, hlsl_extra)
    write_if_changed(GEN_DIR / "triton_d3d12_gen.rs", d3d12_code)

    print(f"gen_rust: Metal {len(metal_kernels)} kernels, D3D12 {len([n for n in metadata if metadata[n].get('d3d12')])} kernels")


if __name__ == "__main__":
    main()
