#ifndef WITCHCRAFT_H
#define WITCHCRAFT_H

/* Generated by cbindgen from src/capi.rs. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct WitchcraftHandle WitchcraftHandle;

typedef struct WitchcraftBytes {
  uint8_t *ptr;
  size_t len;
  int32_t status;
} WitchcraftBytes;

typedef int32_t (*WitchcraftEmbeddingCallback)(uint64_t rowid,
                                               void *user_data,
                                               uint8_t *dst,
                                               size_t dst_cap,
                                               size_t *out_len);

typedef struct WitchcraftSearchHit {
  uint64_t rowid;
  float score;
} WitchcraftSearchHit;

typedef struct WitchcraftSearchResults {
  struct WitchcraftSearchHit *ptr;
  size_t len;
  int32_t status;
} WitchcraftSearchResults;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct WitchcraftHandle *witchcraft_open(const char *db_path, const char *assets_path);

void witchcraft_close(struct WitchcraftHandle *handle);

struct WitchcraftBytes witchcraft_embed(struct WitchcraftHandle *handle,
                                        const uint8_t *body_text,
                                        size_t body_text_len);

int32_t witchcraft_add(struct WitchcraftHandle *handle,
                       uint64_t rowid,
                       const uint8_t *embedding_blob,
                       size_t embedding_blob_len);

int32_t witchcraft_index(struct WitchcraftHandle *handle,
                         WitchcraftEmbeddingCallback embedding_callback,
                         void *user_data);

struct WitchcraftSearchResults witchcraft_search(struct WitchcraftHandle *handle,
                                                 const uint8_t *query,
                                                 size_t query_len,
                                                 float threshold,
                                                 size_t top_k);

void witchcraft_bytes_free(uint8_t *ptr, size_t len);

void witchcraft_search_results_free(struct WitchcraftSearchHit *ptr, size_t len);

const char *witchcraft_last_error(struct WitchcraftHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WITCHCRAFT_H */
