//! Neso-compiled DXIL kernel dispatch for transformer encoders on D3D12.
//!
//! Pre-compiled DXIL bytecode (generated by Triton AOT → HLSL → DXC).
//! All kernels use SM 6.2+ with native half-precision support.

use anyhow::Result;
use candle_d3d12_kernels::{BufferBinding, Gpu, GpuBuffer, ID3D12PipelineState};
use std::sync::Arc;

fn cdiv(a: usize, b: usize) -> usize {
    (a + b - 1) / b
}

// Auto-generated: DXIL constants and Neso pipeline loader.
include!("../kernels/out/generated/neso_d3d12_gen.rs");

fn i32_as_u32(v: i32) -> u32 {
    v as u32
}

pub fn create_f16_buffer(gpu: &Gpu, count: usize) -> Result<GpuBuffer> {
    gpu.create_buffer((count * 2) as u64)
        .map_err(|e| anyhow::anyhow!("create_f16_buffer: {e}"))
}

pub fn create_f32_buffer(gpu: &Gpu, count: usize) -> Result<GpuBuffer> {
    gpu.create_buffer((count * 4) as u64)
        .map_err(|e| anyhow::anyhow!("create_f32_buffer: {e}"))
}

pub fn upload_bytes(gpu: &Gpu, data: &[u8], dst: &GpuBuffer) -> Result<()> {
    gpu.upload_to_buffer(data, dst)
        .map_err(|e| anyhow::anyhow!("upload: {e}"))
}

pub fn download_bytes(gpu: &Gpu, src: &GpuBuffer, size_bytes: u64) -> Result<Vec<u8>> {
    gpu.download_buffer(src, size_bytes)
        .map_err(|e| anyhow::anyhow!("download: {e}"))
}

fn uav_f16<'a>(buf: &'a GpuBuffer, count: u32) -> BufferBinding<'a> {
    BufferBinding::structured_f16(buf, count)
}

fn uav_f32<'a>(buf: &'a GpuBuffer, count: u32) -> BufferBinding<'a> {
    BufferBinding::structured_f32(buf, count)
}

// ── Dispatch functions ──────────────────────────────────────────────────────

pub fn d3d12_copy_f32_f16(kernels: &NesoD3D12Kernels, x: &GpuBuffer, out: &GpuBuffer, n_elements: usize) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;
    let constants = [i32_as_u32(n_elements as i32), grid_x, 1, 1];
    let uavs = [uav_f32(x, n_elements as u32), uav_f16(out, n_elements as u32)];
    kernels
        .gpu
        .record_dispatch(&kernels.copy_f32_f16, &constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("copy_f32_f16 dispatch: {e}"))
}

pub fn d3d12_layer_norm_f32_f16(
    kernels: &NesoD3D12Kernels,
    x: &GpuBuffer,
    weight: &GpuBuffer,
    out: &GpuBuffer,
    n_rows: usize,
    dim: usize,
    eps: f32,
) -> Result<()> {
    let grid_x = n_rows as u32;
    let constants = [
        i32_as_u32(n_rows as i32),
        i32_as_u32(dim as i32),
        eps.to_bits(),
        grid_x,
        1,
        1,
    ];
    let uavs = [
        uav_f32(x, (n_rows * dim) as u32),
        uav_f32(weight, dim as u32),
        uav_f16(out, (n_rows * dim) as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.layer_norm_f32_f16, &constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("layer_norm_f32_f16 dispatch: {e}"))
}

pub fn d3d12_rope_inplace(
    kernels: &NesoD3D12Kernels,
    q: &GpuBuffer,
    k: &GpuBuffer,
    cos: &GpuBuffer,
    sin: &GpuBuffer,
    n_rows: usize,
    row_stride: usize,
    hidden_size: usize,
    head_dim: usize,
) -> Result<()> {
    let pairs = n_rows * hidden_size / 2;
    let grid_x = pairs as u32;
    let constants = [
        i32_as_u32(n_rows as i32),
        i32_as_u32(row_stride as i32),
        i32_as_u32(hidden_size as i32),
        i32_as_u32(head_dim as i32),
        grid_x,
        1,
        1,
    ];
    let uavs = [
        uav_f16(q, (n_rows * hidden_size) as u32),
        uav_f16(k, (n_rows * hidden_size) as u32),
        uav_f32(cos, (row_stride * head_dim / 2) as u32),
        uav_f32(sin, (row_stride * head_dim / 2) as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.rope_inplace, &constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("rope_inplace dispatch: {e}"))
}

/// RMS norm F32→F16: out = half(x / sqrt(mean(x^2) + eps) * weight).
/// UAVs: arg0=x(f32), arg1=weight(f32), arg2=out(f16).
/// cbuffer: arg3=n_rows, arg4=dim, arg5=eps, grid_dims.
pub fn d3d12_rms_norm_f32_f16(
    kernels: &NesoD3D12Kernels,
    x: &GpuBuffer,
    weight: &GpuBuffer,
    out: &GpuBuffer,
    n_rows: usize,
    dim: usize,
    eps: f32,
) -> Result<()> {
    let grid_x = n_rows as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_rows as i32),
        i32_as_u32(dim as i32),
        eps.to_bits(),
        grid_x,
        1,
        1,
    ];
    let uavs = [
        uav_f32(x, (n_rows * dim) as u32),
        uav_f32(weight, dim as u32),
        uav_f16(out, (n_rows * dim) as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.rms_norm_f32_f16, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("rms_norm_f32_f16 dispatch: {e}"))
}

/// Q8 matmul: C[M,N] = A[M,K](fp16) @ B[K,N](packed-4xi8-per-i32) * scales[N](fp16).
/// B weights have 4 int8 values packed per int32 along N dimension.
/// UAVs: arg0=A(f16), arg1=B(packed i32), arg2=C(f16), arg12=scales(f16).
/// cbuffer: arg3=M, arg4=N, arg5=K, arg6-11=strides, grid_dims.
/// Note: arg8 (stride_bk) = N/4, the packed stride.
pub fn d3d12_matmul_q8(
    kernels: &NesoD3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    scales: &GpuBuffer,
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let n_packed = n / 4;
    let grid_x = cdiv(m, 64) as u32;
    let grid_y = cdiv(n, 64) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),        // arg3: M
        i32_as_u32(n as i32),        // arg4: N
        i32_as_u32(k as i32),        // arg5: K
        i32_as_u32(k as i32),        // arg6: stride_am = K
        i32_as_u32(1),               // arg7: stride_ak = 1
        i32_as_u32(n_packed as i32), // arg8: stride_bk = N/4 (packed)
        i32_as_u32(1),               // arg9: stride_bn = 1
        i32_as_u32(n as i32),        // arg10: stride_cm = N
        i32_as_u32(1),               // arg11: stride_cn = 1
        grid_x,
        grid_y,
        1,
    ];
    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f32(b, (k * n_packed) as u32), // packed: 4 int8s per int32
        uav_f16(out, (m * n) as u32),
        uav_f16(scales, n as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.matmul_q8_64x64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_q8 dispatch: {e}"))
}

/// FP16 matmul: C[M,N] = A[M,K] @ B[K,N], all fp16.
pub fn d3d12_matmul_fp16(
    kernels: &NesoD3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let grid_x = cdiv(m, 64) as u32;
    let grid_y = cdiv(n, 64) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),
        i32_as_u32(n as i32),
        i32_as_u32(k as i32),
        i32_as_u32(k as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        grid_x,
        grid_y,
        1,
    ];
    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f16(b, (k * n) as u32),
        uav_f16(out, (m * n) as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.matmul_fp16_64x64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_fp16 dispatch: {e}"))
}

/// Fused gated-GELU: out = GELU(gate) * up, all fp16.
/// UAVs: arg0=gate(f16), arg1=up(f16), arg2=out(f16).
/// cbuffer: arg3=n_elements, grid_dims.
pub fn d3d12_gelu_mul(
    kernels: &NesoD3D12Kernels,
    gate: &GpuBuffer,
    up: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;
    let root_constants: Vec<u32> = vec![i32_as_u32(n_elements as i32), grid_x, 1, 1];
    let uavs = [
        uav_f16(gate, n_elements as u32),
        uav_f16(up, n_elements as u32),
        uav_f16(out, n_elements as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.gelu_mul, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("gelu_mul dispatch: {e}"))
}

/// Mixed-precision residual add: out[i] = float(a_f16[i]) + b_f32[i].
/// UAVs: arg0=a(f16), arg1=b(f32), arg2=out(f32).
/// cbuffer: arg3=n_elements, grid_dims.
pub fn d3d12_residual_add_f16_f32(
    kernels: &NesoD3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;
    let root_constants: Vec<u32> = vec![i32_as_u32(n_elements as i32), grid_x, 1, 1];
    let uavs = [
        uav_f16(a, n_elements as u32),
        uav_f32(b, n_elements as u32),
        uav_f32(out, n_elements as u32),
    ];
    kernels
        .gpu
        .record_dispatch(&kernels.residual_add_f16_f32, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("residual_add_f16_f32 dispatch: {e}"))
}

/// Batched Flash Attention 2 with procedural local/padding masks.
/// UAVs: arg0=Q(f16), arg1=K(f16), arg2=V(f16), arg3=O(f16), arg4=lengths(i32).
pub fn d3d12_flash_attention_bias(
    kernels: &NesoD3D12Kernels,
    q: &GpuBuffer,
    k: &GpuBuffer,
    v: &GpuBuffer,
    out: &GpuBuffer,
    lengths: &GpuBuffer,
    local_mask: &GpuBuffer,
    batch_size: usize,
    n_heads: usize,
    seq_len: usize,
    padded_seq: usize,
    use_local_mask: bool,
    head_dim: usize,
    stride_h: i32,
    stride_m: i32,
    stride_o: i32,
    sm_scale: f32,
) -> Result<()> {
    let grid_x = cdiv(seq_len, 32) as u32;
    let grid_y = (batch_size * n_heads) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(seq_len as i32),
        i32_as_u32(n_heads as i32),
        i32_as_u32((padded_seq * n_heads * head_dim) as i32),
        i32_as_u32(use_local_mask as i32),
        i32_as_u32(padded_seq as i32),
        i32_as_u32(stride_h),
        i32_as_u32(stride_m),
        i32_as_u32(stride_o),
        sm_scale.to_bits(),
        grid_x,
        grid_y,
        1,
    ];
    let n_elem = (batch_size * padded_seq * n_heads * head_dim) as u32;
    let uavs = [
        uav_f16(q, n_elem),
        uav_f16(k, n_elem),
        uav_f16(v, n_elem),
        uav_f16(out, n_elem),
        uav_f32(lengths, batch_size as u32),
        uav_f32(local_mask, (padded_seq * padded_seq) as u32),
    ];
    kernels
        .gpu
        .record_dispatch(
            &kernels.flash_attention_bias_d64,
            &root_constants,
            &uavs,
            [grid_x, grid_y, 1],
        )
        .map_err(|e| anyhow::anyhow!("flash_attention_bias dispatch: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn buffer_f16(gpu: &Gpu, values: &[half::f16]) -> Result<GpuBuffer> {
        let buffer = create_f16_buffer(gpu, values.len())?;
        let bytes = values.iter().flat_map(|value| value.to_le_bytes()).collect::<Vec<_>>();
        upload_bytes(gpu, &bytes, &buffer)?;
        Ok(buffer)
    }

    fn buffer_f32(gpu: &Gpu, values: &[f32]) -> Result<GpuBuffer> {
        let buffer = create_f32_buffer(gpu, values.len())?;
        let bytes = values.iter().flat_map(|value| value.to_le_bytes()).collect::<Vec<_>>();
        upload_bytes(gpu, &bytes, &buffer)?;
        Ok(buffer)
    }

    #[test]
    fn neso_d3d12_batched_matmul_matches_reference() -> Result<()> {
        let gpu = Arc::new(Gpu::new(0)?);
        let kernels = NesoD3D12Kernels::load(&gpu)?;
        let (m, n, k) = (128usize, 64usize, 64usize);
        let av = (0..m * k)
            .map(|i| half::f16::from_f32(((i * 17 % 31) as f32 - 15.0) / 19.0))
            .collect::<Vec<_>>();
        let bv = (0..k * n)
            .map(|i| half::f16::from_f32(((i * 11 % 29) as f32 - 14.0) / 23.0))
            .collect::<Vec<_>>();
        let a = buffer_f16(&gpu, &av)?;
        let b = buffer_f16(&gpu, &bv)?;
        let out = create_f16_buffer(&gpu, m * n)?;
        gpu.begin_batch().map_err(|e| anyhow::anyhow!("begin_batch: {e}"))?;
        d3d12_matmul_fp16(&kernels, &a, &b, &out, m, n, k)?;
        gpu.end_batch().map_err(|e| anyhow::anyhow!("end_batch: {e}"))?;
        let bytes = download_bytes(&gpu, &out, (m * n * 2) as u64)?;
        let got = bytes
            .chunks_exact(2)
            .map(|value| half::f16::from_le_bytes([value[0], value[1]]).to_f32())
            .collect::<Vec<_>>();
        for row in 0..m {
            for column in 0..n {
                let expected = (0..k)
                    .map(|inner| av[row * k + inner].to_f32() * bv[inner * n + column].to_f32())
                    .sum::<f32>();
                anyhow::ensure!((got[row * n + column] - expected).abs() < 0.03);
            }
        }
        Ok(())
    }

    #[test]
    fn neso_d3d12_batched_rope_matches_reference() -> Result<()> {
        let gpu = Arc::new(Gpu::new(0)?);
        let kernels = NesoD3D12Kernels::load(&gpu)?;
        let (batch, padded, hidden, head_dim) = (2usize, 64usize, 128usize, 64usize);
        let rows = batch * padded;
        let original = (0..rows * hidden)
            .map(|i| half::f16::from_f32(((i * 17 % 131) as f32 - 65.0) / 37.0))
            .collect::<Vec<_>>();
        let trig = (0..padded * head_dim / 2).map(|i| i as f32 / 113.0).collect::<Vec<_>>();
        let cosv = trig.iter().map(|value| value.cos()).collect::<Vec<_>>();
        let sinv = trig.iter().map(|value| value.sin()).collect::<Vec<_>>();
        let q = buffer_f16(&gpu, &original)?;
        let k = buffer_f16(&gpu, &original)?;
        let cos = buffer_f32(&gpu, &cosv)?;
        let sin = buffer_f32(&gpu, &sinv)?;
        gpu.begin_batch().map_err(|e| anyhow::anyhow!("begin_batch: {e}"))?;
        d3d12_rope_inplace(&kernels, &q, &k, &cos, &sin, rows, padded, hidden, head_dim)?;
        gpu.end_batch().map_err(|e| anyhow::anyhow!("end_batch: {e}"))?;
        let bytes = download_bytes(&gpu, &q, (original.len() * 2) as u64)?;
        let got = bytes
            .chunks_exact(2)
            .map(|value| half::f16::from_le_bytes([value[0], value[1]]).to_f32())
            .collect::<Vec<_>>();
        for row in 0..rows {
            let token = row % padded;
            for head in 0..hidden / head_dim {
                for d in 0..head_dim / 2 {
                    let first = row * hidden + head * head_dim + d;
                    let second = first + head_dim / 2;
                    let trig_index = token * head_dim / 2 + d;
                    let a = original[first].to_f32();
                    let b = original[second].to_f32();
                    let expected = a * cosv[trig_index] - b * sinv[trig_index];
                    anyhow::ensure!((got[first] - expected).abs() < 0.003);
                }
            }
        }
        Ok(())
    }

    #[test]
    fn neso_d3d12_batched_flash_attention_matches_reference() -> Result<()> {
        let gpu = Arc::new(Gpu::new(0)?);
        let kernels = NesoD3D12Kernels::load(&gpu)?;
        let (batch, heads, seq, dim) = (2usize, 2usize, 7usize, 64usize);
        let sequence_lengths = [seq, 5usize];
        let values = |factor, modulus, center, divisor| -> Vec<half::f16> {
            (0..batch * seq * heads * dim)
                .map(|i| half::f16::from_f32(((i * factor % modulus) as f32 - center) / divisor))
                .collect()
        };
        let qv = values(17, 31, 15.0, 19.0);
        let kv = values(11, 29, 14.0, 23.0);
        let vv = values(7, 37, 18.0, 17.0);
        let q = buffer_f16(&gpu, &qv)?;
        let k = buffer_f16(&gpu, &kv)?;
        let v = buffer_f16(&gpu, &vv)?;
        let out = create_f16_buffer(&gpu, batch * seq * heads * dim)?;
        let lengths = create_f32_buffer(&gpu, batch)?;
        let length_bytes = sequence_lengths
            .iter()
            .flat_map(|&length| (length as u32).to_le_bytes())
            .collect::<Vec<_>>();
        upload_bytes(&gpu, &length_bytes, &lengths)?;
        let local_mask = buffer_f32(&gpu, &vec![0.0; seq * seq])?;

        gpu.begin_batch().map_err(|e| anyhow::anyhow!("begin_batch: {e}"))?;
        d3d12_flash_attention_bias(
            &kernels,
            &q,
            &k,
            &v,
            &out,
            &lengths,
            &local_mask,
            batch,
            heads,
            seq,
            seq,
            false,
            dim,
            dim as i32,
            (heads * dim) as i32,
            (heads * dim) as i32,
            1.0 / 8.0,
        )?;
        gpu.end_batch().map_err(|e| anyhow::anyhow!("end_batch: {e}"))?;
        let bytes = download_bytes(&gpu, &out, (batch * seq * heads * dim * 2) as u64)?;
        let got = bytes
            .chunks_exact(2)
            .map(|b| half::f16::from_le_bytes([b[0], b[1]]).to_f32())
            .collect::<Vec<_>>();

        for batch_index in 0..batch {
            for head in 0..heads {
                for query in 0..seq {
                    let valid_len = sequence_lengths[batch_index];
                    let base = batch_index * seq * heads * dim;
                    let mut scores = vec![0.0f32; valid_len];
                    for key in 0..valid_len {
                        for d in 0..dim {
                            scores[key] += qv[base + query * heads * dim + head * dim + d].to_f32()
                                * kv[base + key * heads * dim + head * dim + d].to_f32()
                                / 8.0;
                        }
                    }
                    let max = scores.iter().copied().fold(f32::NEG_INFINITY, f32::max);
                    let sum: f32 = scores
                        .iter_mut()
                        .map(|x| {
                            *x = (*x - max).exp();
                            *x
                        })
                        .sum();
                    for d in 0..dim {
                        let expected: f32 = (0..valid_len)
                            .map(|key| scores[key] / sum * vv[base + key * heads * dim + head * dim + d].to_f32())
                            .sum();
                        let actual = got[base + query * heads * dim + head * dim + d];
                        anyhow::ensure!(
                            (actual - expected).abs() < 0.03,
                            "b={batch_index} h={head} q={query} d={d}: {actual} vs {expected}"
                        );
                    }
                }
            }
        }
        Ok(())
    }
}
