//! Triton-compiled DXIL kernel dispatch for T5 encoder on D3D12.
//!
//! Pre-compiled DXIL bytecode (generated by Triton AOT → HLSL → DXC).
//! All kernels use SM 6.2+ with native half-precision support.

use anyhow::Result;
use candle_d3d12_kernels::{BufferBinding, Gpu, GpuBuffer, ID3D12PipelineState};
use std::sync::Arc;

fn cdiv(a: usize, b: usize) -> usize {
    (a + b - 1) / b
}

// Auto-generated: DXIL constants, T5D3D12Kernels struct + load().
include!("../kernels/out/generated/triton_d3d12_gen.rs");

fn i32_as_u32(v: i32) -> u32 {
    v as u32
}

pub fn create_f16_buffer(gpu: &Gpu, count: usize) -> Result<GpuBuffer> {
    gpu.create_buffer((count * 2) as u64)
        .map_err(|e| anyhow::anyhow!("create_f16_buffer: {e}"))
}

pub fn create_f32_buffer(gpu: &Gpu, count: usize) -> Result<GpuBuffer> {
    gpu.create_buffer((count * 4) as u64)
        .map_err(|e| anyhow::anyhow!("create_f32_buffer: {e}"))
}

pub fn upload_bytes(gpu: &Gpu, data: &[u8], dst: &GpuBuffer) -> Result<()> {
    gpu.upload_to_buffer(data, dst)
        .map_err(|e| anyhow::anyhow!("upload: {e}"))
}

pub fn download_bytes(gpu: &Gpu, src: &GpuBuffer, size_bytes: u64) -> Result<Vec<u8>> {
    gpu.download_buffer(src, size_bytes)
        .map_err(|e| anyhow::anyhow!("download: {e}"))
}

fn uav_f16<'a>(buf: &'a GpuBuffer, count: u32) -> BufferBinding<'a> {
    BufferBinding::structured_f16(buf, count)
}

fn uav_f32<'a>(buf: &'a GpuBuffer, count: u32) -> BufferBinding<'a> {
    BufferBinding::structured_f32(buf, count)
}

// ── Dispatch functions ──────────────────────────────────────────────────────

/// RMS norm F32→F16: out = half(x / sqrt(mean(x^2) + eps) * weight).
/// UAVs: arg0=x(f32), arg1=weight(f32), arg2=out(f16).
/// cbuffer: arg3=n_rows, arg4=dim, arg5=eps, grid_dims.
pub fn d3d12_rms_norm_f32_f16(
    kernels: &T5D3D12Kernels,
    x: &GpuBuffer,
    weight: &GpuBuffer,
    out: &GpuBuffer,
    n_rows: usize,
    dim: usize,
    eps: f32,
) -> Result<()> {
    let grid_x = n_rows as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_rows as i32),
        i32_as_u32(dim as i32),
        eps.to_bits(),
        grid_x, 1, 1,
    ];
    let uavs = [
        uav_f32(x, (n_rows * dim) as u32),
        uav_f32(weight, dim as u32),
        uav_f16(out, (n_rows * dim) as u32),
    ];
    kernels.gpu.record_dispatch(&kernels.rms_norm_f32_f16, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("rms_norm_f32_f16 dispatch: {e}"))
}

/// Q8 matmul: C[M,N] = A[M,K](fp16) @ B[K,N](packed-4xi8-per-i32) * scales[N](fp16).
/// B weights have 4 int8 values packed per int32 along N dimension.
/// UAVs: arg0=A(f16), arg1=B(packed i32), arg2=C(f16), arg12=scales(f16).
/// cbuffer: arg3=M, arg4=N, arg5=K, arg6-11=strides, grid_dims.
/// Note: arg8 (stride_bk) = N/4, the packed stride.
pub fn d3d12_matmul_q8(
    kernels: &T5D3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    scales: &GpuBuffer,
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let n_packed = n / 4;
    let grid_x = cdiv(m, 64) as u32;
    let grid_y = cdiv(n, 64) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),         // arg3: M
        i32_as_u32(n as i32),         // arg4: N
        i32_as_u32(k as i32),         // arg5: K
        i32_as_u32(k as i32),         // arg6: stride_am = K
        i32_as_u32(1),                // arg7: stride_ak = 1
        i32_as_u32(n_packed as i32),  // arg8: stride_bk = N/4 (packed)
        i32_as_u32(1),                // arg9: stride_bn = 1
        i32_as_u32(n as i32),         // arg10: stride_cm = N
        i32_as_u32(1),                // arg11: stride_cn = 1
        grid_x, grid_y, 1,
    ];
    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f32(b, (k * n_packed) as u32), // packed: 4 int8s per int32
        uav_f16(out, (m * n) as u32),
        uav_f16(scales, n as u32),
    ];
    kernels.gpu.record_dispatch(&kernels.matmul_q8_64x64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_q8 dispatch: {e}"))
}

/// FP16 matmul: C[M,N] = A[M,K] @ B[K,N], all fp16.
pub fn d3d12_matmul_fp16(
    kernels: &T5D3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    m: usize,
    n: usize,
    k: usize,
) -> Result<()> {
    let grid_x = cdiv(m, 64) as u32;
    let grid_y = cdiv(n, 64) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(m as i32),
        i32_as_u32(n as i32),
        i32_as_u32(k as i32),
        i32_as_u32(k as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        i32_as_u32(n as i32),
        i32_as_u32(1),
        grid_x, grid_y, 1,
    ];
    let uavs = [
        uav_f16(a, (m * k) as u32),
        uav_f16(b, (k * n) as u32),
        uav_f16(out, (m * n) as u32),
    ];
    kernels.gpu.record_dispatch(&kernels.matmul_fp16_64x64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("matmul_fp16 dispatch: {e}"))
}

/// Fused gated-GELU: out = GELU(gate) * up, all fp16.
/// UAVs: arg0=gate(f16), arg1=up(f16), arg2=out(f16).
/// cbuffer: arg3=n_elements, grid_dims.
pub fn d3d12_gelu_mul(
    kernels: &T5D3D12Kernels,
    gate: &GpuBuffer,
    up: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];
    let uavs = [
        uav_f16(gate, n_elements as u32),
        uav_f16(up, n_elements as u32),
        uav_f16(out, n_elements as u32),
    ];
    kernels.gpu.record_dispatch(&kernels.gelu_mul, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("gelu_mul dispatch: {e}"))
}

/// Mixed-precision residual add: out[i] = float(a_f16[i]) + b_f32[i].
/// UAVs: arg0=a(f16), arg1=b(f32), arg2=out(f32).
/// cbuffer: arg3=n_elements, grid_dims.
pub fn d3d12_residual_add_f16_f32(
    kernels: &T5D3D12Kernels,
    a: &GpuBuffer,
    b: &GpuBuffer,
    out: &GpuBuffer,
    n_elements: usize,
) -> Result<()> {
    let grid_x = cdiv(n_elements, 1024) as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(n_elements as i32),
        grid_x, 1, 1,
    ];
    let uavs = [
        uav_f16(a, n_elements as u32),
        uav_f32(b, n_elements as u32),
        uav_f32(out, n_elements as u32),
    ];
    kernels.gpu.record_dispatch(&kernels.residual_add_f16_f32, &root_constants, &uavs, [grid_x, 1, 1])
        .map_err(|e| anyhow::anyhow!("residual_add_f16_f32 dispatch: {e}"))
}

/// Flash Attention 2 with additive position bias.
/// UAVs: arg0=Q(f16), arg1=K(f16), arg2=V(f16), arg3=O(f16), arg4=bias(f32).
/// cbuffer: arg5=seq_len, arg6=stride_h, arg7=stride_m, arg8=stride_o, arg9=sm_scale, grid_dims.
pub fn d3d12_flash_attention_bias(
    kernels: &T5D3D12Kernels,
    q: &GpuBuffer,
    k: &GpuBuffer,
    v: &GpuBuffer,
    out: &GpuBuffer,
    bias: &GpuBuffer,
    n_heads: usize,
    seq_len: usize,
    head_dim: usize,
    stride_h: i32,
    stride_m: i32,
    stride_o: i32,
    sm_scale: f32,
) -> Result<()> {
    let grid_x = cdiv(seq_len, 32) as u32;
    let grid_y = n_heads as u32;
    let root_constants: Vec<u32> = vec![
        i32_as_u32(seq_len as i32),
        i32_as_u32(stride_h),
        i32_as_u32(stride_m),
        i32_as_u32(stride_o),
        sm_scale.to_bits(),
        grid_x, grid_y, 1,
    ];
    let n_elem = (n_heads * seq_len * head_dim) as u32;
    let uavs = [
        uav_f16(q, n_elem),
        uav_f16(k, n_elem),
        uav_f16(v, n_elem),
        uav_f16(out, n_elem),
        uav_f32(bias, (n_heads * seq_len * seq_len) as u32),
    ];
    kernels.gpu.record_dispatch(&kernels.flash_attention_bias_d64, &root_constants, &uavs, [grid_x, grid_y, 1])
        .map_err(|e| anyhow::anyhow!("flash_attention_bias dispatch: {e}"))
}
